#############################################################################
# Makefile for building: bookshelf
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? ??? 29 19:43:26 2017
# Project:  books.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile books.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtSql -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		data.cpp \
		assesment.cpp \
		editdialog.cpp \
		addquotesdialog.cpp \
		quote.cpp \
		settingswindow.cpp moc_mainwindow.cpp \
		moc_assesment.cpp \
		moc_editdialog.cpp \
		moc_addquotesdialog.cpp \
		moc_settingswindow.cpp \
		qrc_rsc.cpp
OBJECTS       = main.o \
		mainwindow.o \
		data.o \
		assesment.o \
		editdialog.o \
		addquotesdialog.o \
		quote.o \
		settingswindow.o \
		moc_mainwindow.o \
		moc_assesment.o \
		moc_editdialog.o \
		moc_addquotesdialog.o \
		moc_settingswindow.o \
		qrc_rsc.o
DIST          = resource/books.sqlite \
		resource/books.xml \
		resource/bookPic.jpg \
		resource/netu.jpg \
		resource/picButtons/textbold.png \
		resource/picButtons/textcenter.png \
		resource/picButtons/textitalic.png \
		resource/picButtons/textjustify.png \
		resource/picButtons/textleft.png \
		resource/picButtons/textright.png \
		resource/picButtons/textunder.png \
		resource/empty.png \
		resource/star_fill.png \
		resource/star_no_fill.png \
		resource/bookcase.ico \
		resource/bookPic.ico \
		resource/styles/black.css \
		resource/styles/QTDark.css \
		resource/qml/main \
		(copy).qml \
		resource/qml/main.qml \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		books.pro
QMAKE_TARGET  = bookshelf
DESTDIR       = 
TARGET        = bookshelf

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_assesment.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: books.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile books.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile books.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/bookshelf1.0.0 || $(MKDIR) .tmp/bookshelf1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/bookshelf1.0.0/ && $(COPY_FILE) --parents mainwindow.h data.h assesment.h initdb.h editdialog.h addquotesdialog.h quote.h settingswindow.h .tmp/bookshelf1.0.0/ && $(COPY_FILE) --parents resource/rsc.qrc .tmp/bookshelf1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp data.cpp assesment.cpp editdialog.cpp addquotesdialog.cpp quote.cpp settingswindow.cpp .tmp/bookshelf1.0.0/ && $(COPY_FILE) --parents mainwindow.ui assesment.ui .tmp/bookshelf1.0.0/ && (cd `dirname .tmp/bookshelf1.0.0` && $(TAR) bookshelf1.0.0.tar bookshelf1.0.0 && $(COMPRESS) bookshelf1.0.0.tar) && $(MOVE) `dirname .tmp/bookshelf1.0.0`/bookshelf1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/bookshelf1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_assesment.cpp moc_editdialog.cpp moc_addquotesdialog.cpp moc_settingswindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_assesment.cpp moc_editdialog.cpp moc_addquotesdialog.cpp moc_settingswindow.cpp
moc_mainwindow.cpp: data.h \
		editdialog.h \
		assesment.h \
		addquotesdialog.h \
		quote.h \
		settingswindow.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_assesment.cpp: assesment.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) assesment.h -o moc_assesment.cpp

moc_editdialog.cpp: data.h \
		assesment.h \
		editdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) editdialog.h -o moc_editdialog.cpp

moc_addquotesdialog.cpp: addquotesdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) addquotesdialog.h -o moc_addquotesdialog.cpp

moc_settingswindow.cpp: settingswindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) settingswindow.h -o moc_settingswindow.cpp

compiler_rcc_make_all: qrc_rsc.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_rsc.cpp
qrc_rsc.cpp: resource/rsc.qrc \
		resource/bookPic.jpg \
		resource/empty.png \
		resource/netu.jpg \
		resource/star_no_fill.png \
		resource/bookcase.ico \
		resource/star_fill.png \
		resource/qml/main.qml \
		resource/styles/black.css \
		resource/styles/QTDark.css \
		resource/picButtons/textright.png \
		resource/picButtons/textunder.png \
		resource/picButtons/textcenter.png \
		resource/picButtons/textleft.png \
		resource/picButtons/textjustify.png \
		resource/picButtons/textbold.png \
		resource/picButtons/textitalic.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name rsc resource/rsc.qrc -o qrc_rsc.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_assesment.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_assesment.h
ui_mainwindow.h: mainwindow.ui \
		assesment.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_assesment.h: assesment.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic assesment.ui -o ui_assesment.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		data.h \
		editdialog.h \
		assesment.h \
		addquotesdialog.h \
		quote.h \
		settingswindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		data.h \
		editdialog.h \
		assesment.h \
		addquotesdialog.h \
		quote.h \
		settingswindow.h \
		ui_mainwindow.h \
		initdb.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

data.o: data.cpp data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data.o data.cpp

assesment.o: assesment.cpp assesment.h \
		ui_assesment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o assesment.o assesment.cpp

editdialog.o: editdialog.cpp editdialog.h \
		data.h \
		assesment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editdialog.o editdialog.cpp

addquotesdialog.o: addquotesdialog.cpp addquotesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addquotesdialog.o addquotesdialog.cpp

quote.o: quote.cpp quote.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quote.o quote.cpp

settingswindow.o: settingswindow.cpp settingswindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingswindow.o settingswindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_assesment.o: moc_assesment.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_assesment.o moc_assesment.cpp

moc_editdialog.o: moc_editdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editdialog.o moc_editdialog.cpp

moc_addquotesdialog.o: moc_addquotesdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addquotesdialog.o moc_addquotesdialog.cpp

moc_settingswindow.o: moc_settingswindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingswindow.o moc_settingswindow.cpp

qrc_rsc.o: qrc_rsc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_rsc.o qrc_rsc.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

